apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: my-flask-app
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_PASSWORD_FILE
          value: db/password.txt
      volumes:
      - name: db-password
        secret:
          secretName: db-password

